prod_media_distribution_domain_name = "du2rzaik0l8gr.cloudfront.net"
prod_web_distribution_domain_name   = "d1owc73xlyegzt.cloudfront.net"
firebase_prod_project_id            = "heart-of-yours"
prod_api_domain_name                = "d-xlaoclzncj.execute-api.ca-central-1.amazonaws.com"
prod_mcp_distribution_domain_name   = "dechah25v67t4.cloudfront.net"
