"""
Generate the month-token table the API's Hevy CSV importer reads.

Reads:
  - ../content/imports/hevy/months.json: the month token the Hevy app writes
    in its export dates, per language, copied from real exports

Writes:
  - ../api/lib/models/hevy_months.dart: one const map, formatted

The app's export writes dates as `d MMM yyyy, HH:mm` with the month in the
app's language. No token means two different months in any pair of
languages (asserted here), so one table reads every language without
detecting which. Re-run after editing the JSON:

    uv run scripts/hevy_months.py
"""

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MONTHS = ROOT / 'content' / 'imports' / 'hevy' / 'months.json'
OUT = ROOT / 'api' / 'lib' / 'models' / 'hevy_months.dart'


def month_key(token: str) -> str:
    """The form a month token is looked up in: case-folded, no trailing dot."""
    return token.lower().rstrip('.')


def months() -> dict[str, int]:
    table: dict[str, int] = {}
    for lang, tokens in json.loads(MONTHS.read_text()).items():
        assert len(tokens) == 12, f'{lang}: {len(tokens)} month tokens'
        for i, token in enumerate(tokens, start=1):
            key = month_key(token)
            assert table.get(key, i) == i, f'{key!r} is month {table[key]} and {i}'
            table[key] = i
    return dict(sorted(table.items()))


def dart_string(s: str) -> str:
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


def main() -> None:
    table = months()
    lines = [
        '// Generated by scripts/hevy_months.py from content/imports/hevy/months.json — do not edit.',
        '',
        "/// A month token as Hevy's app writes it in an export date, in any of its",
        '/// languages (case-folded, trailing dot dropped) → month number. One table',
        '/// serves every language: no token means two different months anywhere.',
        'const hevyMonths = <String, int>{',
        *(f'  {dart_string(k)}: {v},' for k, v in table.items()),
        '};',
        '',
    ]
    OUT.write_text('\n'.join(lines))
    subprocess.run(['dart', 'format', str(OUT)], check=True, capture_output=True)
    print(f'{len(table)} month tokens → {OUT}')


if __name__ == '__main__':
    main()
