"""
Generate the Hevy lookup tables the API's CSV importer reads.

Reads:
  - ../content/imports/hevy/catalog.json: Hevy's own exercise catalog with each
    title in all of Hevy's languages (454 entries: the 451 the public API
    lists plus 3 archived ones that old histories still carry)
  - ../content/imports/hevy/months.json: the month token the Hevy app writes
    in its export dates, per language, copied from real exports

Writes:
  - ../api/lib/models/hevy_catalog.dart: two const maps, formatted

The app's CSV export translates catalog exercise titles into the app's
language and writes dates as `d MMM yyyy, HH:mm` with a translated month, so
the importer needs the reverse of both. Twelve translated titles are shared by
two catalog exercises; the table picks one deterministically (a live exercise
over an archived one, then the first in catalog order) and the picks are
listed in the generated file's header. Re-run after editing either
JSON:

    uv run scripts/hevy_catalog.py
"""

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / 'content' / 'imports' / 'hevy' / 'catalog.json'
MONTHS = ROOT / 'content' / 'imports' / 'hevy' / 'months.json'
OUT = ROOT / 'api' / 'lib' / 'models' / 'hevy_catalog.dart'


def month_key(token: str) -> str:
    """The form a month token is looked up in: case-folded, no trailing dot."""
    return token.lower().rstrip('.')


def months() -> dict[str, int]:
    table: dict[str, int] = {}
    for lang, tokens in json.loads(MONTHS.read_text()).items():
        assert len(tokens) == 12, f'{lang}: {len(tokens)} month tokens'
        for i, token in enumerate(tokens, start=1):
            key = month_key(token)
            assert table.get(key, i) == i, f'{key!r} is month {table[key]} and {i}'
            table[key] = i
    return dict(sorted(table.items()))


def titles() -> tuple[dict[str, str], list[tuple[str, list[str], str]]]:
    catalog = json.loads(CATALOG.read_text())
    english = {e['title'] for e in catalog}
    # translated title -> the catalog entries carrying it, in catalog order; an
    # English title is already canonical, whichever entry's translation it is
    carriers: dict[str, list[dict]] = {}
    for entry in catalog:
        for title in entry['titles'].values():
            if title not in english:
                carriers.setdefault(title, []).append(entry)
    table: dict[str, str] = {}
    ambiguous: list[tuple[str, list[str], str]] = []
    for title, entries in carriers.items():
        names = sorted({e['title'] for e in entries})
        pick = min(entries, key=lambda e: (e['archived'], catalog.index(e)))
        table[title] = pick['title']
        if len(names) > 1:
            ambiguous.append((title, names, pick['title']))
    return dict(sorted(table.items())), ambiguous


def dart_string(s: str) -> str:
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


def main() -> None:
    month_table = months()
    title_table, ambiguous = titles()
    lines = [
        '// Generated by scripts/hevy_catalog.py from content/imports/hevy/ — do not edit.',
        '//',
        '// What the Hevy app writes in its CSV export, mapped back: the month tokens',
        '// of its dates (one table for every language, since no token means two',
        '// different months anywhere) and the translated catalog titles. Titles',
        '// shared by two catalog exercises resolve to one of them; the picks:',
        *(f'//   {dart_string(t)}: {" / ".join(n)} → {p}' for t, n, p in ambiguous),
        '',
        "/// A month token as Hevy's app writes it (case-folded, trailing dot",
        '/// dropped) → month number.',
        'const hevyMonths = <String, int>{',
        *(f'  {dart_string(k)}: {v},' for k, v in month_table.items()),
        '};',
        '',
        '/// A catalog title as the app writes it in any non-English language → the',
        '/// English catalog title. English titles and custom exercises are absent.',
        'const hevyTitles = <String, String>{',
        *(f'  {dart_string(k)}: {dart_string(v)},' for k, v in title_table.items()),
        '};',
        '',
    ]
    OUT.write_text('\n'.join(lines))
    subprocess.run(['dart', 'format', str(OUT)], check=True, capture_output=True)
    print(f'{len(month_table)} month tokens, {len(title_table)} titles, {len(ambiguous)} ambiguous → {OUT}')


if __name__ == '__main__':
    main()
