// Mocks generated by Mockito 5.4.6 from annotations
// in heart_models/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:heart_models/src/models/charts.dart' as _i3;
import 'package:heart_models/src/models/exercise.dart' as _i2;
import 'package:heart_models/src/models/misc.dart' as _i6;
import 'package:heart_models/src/models/stats.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMuscleTagging_0 extends _i1.SmartFake implements _i2.MuscleTagging {
  _FakeMuscleTagging_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeMovement_1 extends _i1.SmartFake implements _i2.Movement {
  _FakeMovement_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeExercise_2 extends _i1.SmartFake implements _i2.Exercise {
  _FakeExercise_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeChartPreference_3 extends _i1.SmartFake implements _i3.ChartPreference {
  _FakeChartPreference_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutSummary].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSummary extends _i1.Mock implements _i4.WorkoutSummary {
  MockWorkoutSummary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [Exercise].
///
/// See the documentation for Mockito's code generation for more information.
class MockExercise extends _i1.Mock implements _i2.Exercise {
  MockExercise() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i2.Category get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i2.Category.weightedBodyWeight,
          )
          as _i2.Category);

  @override
  _i2.Target get target =>
      (super.noSuchMethod(
            Invocation.getter(#target),
            returnValue: _i2.Target.core,
          )
          as _i2.Target);

  @override
  bool get hasInfo => (super.noSuchMethod(Invocation.getter(#hasInfo), returnValue: false) as bool);

  @override
  bool get isMine => (super.noSuchMethod(Invocation.getter(#isMine), returnValue: false) as bool);

  @override
  bool get isArchived => (super.noSuchMethod(Invocation.getter(#isArchived), returnValue: false) as bool);

  @override
  _i2.MuscleTagging get muscles =>
      (super.noSuchMethod(
            Invocation.getter(#muscles),
            returnValue: _FakeMuscleTagging_0(
              this,
              Invocation.getter(#muscles),
            ),
          )
          as _i2.MuscleTagging);

  @override
  _i2.Movement get movement =>
      (super.noSuchMethod(
            Invocation.getter(#movement),
            returnValue: _FakeMovement_1(this, Invocation.getter(#movement)),
          )
          as _i2.Movement);

  @override
  bool fits(Iterable<_i2.ExerciseFilter>? filters) =>
      (super.noSuchMethod(
            Invocation.method(#fits, [filters]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.Exercise copyWith({
    _i2.Category? category,
    _i2.Target? target,
    ({int? height, String link, int? width})? asset,
    ({int? height, String link, int? width})? thumbnail,
    bool? isMine,
    String? instructions,
    bool? isArchived,
    _i2.MuscleTagging? tags,
    _i2.Movement? movement,
    _i6.MeasurementUnit? unitSystem,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #category: category,
              #target: target,
              #asset: asset,
              #thumbnail: thumbnail,
              #isMine: isMine,
              #instructions: instructions,
              #isArchived: isArchived,
              #tags: tags,
              #movement: movement,
              #unitSystem: unitSystem,
            }),
            returnValue: _FakeExercise_2(
              this,
              Invocation.method(#copyWith, [], {
                #category: category,
                #target: target,
                #asset: asset,
                #thumbnail: thumbnail,
                #isMine: isMine,
                #instructions: instructions,
                #isArchived: isArchived,
                #tags: tags,
                #movement: movement,
                #unitSystem: unitSystem,
              }),
            ),
          )
          as _i2.Exercise);

  @override
  bool contains(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [query]),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  int compareTo(_i2.Exercise? other) =>
      (super.noSuchMethod(
            Invocation.method(#compareTo, [other]),
            returnValue: 0,
          )
          as int);
}

/// A class which mocks [ChartPreference].
///
/// See the documentation for Mockito's code generation for more information.
class MockChartPreference extends _i1.Mock implements _i3.ChartPreference {
  MockChartPreference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChartPreferenceType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i3.ChartPreferenceType.maxConsecutiveReps,
          )
          as _i3.ChartPreferenceType);

  @override
  _i3.ChartPreference copyWith({
    String? id,
    _i3.ChartPreferenceType? type,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #type: type,
              #data: data,
            }),
            returnValue: _FakeChartPreference_3(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #type: type,
                #data: data,
              }),
            ),
          )
          as _i3.ChartPreference);

  @override
  Map<String, dynamic> toRow() =>
      (super.noSuchMethod(
            Invocation.method(#toRow, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
