name: "Sync Exercise library, dev"

on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
    paths:
      - content/exercise_library.yml
      - content/exercise_library_schema.json
      - scripts/library_locales.py
      - .github/workflows/exercise-library.yml
      - .github/workflows/exercise-library-dev.yml

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/exercise-library.yml
    with:
      AWS_ROLE: 'arn:aws:iam::583168578067:role/heart-github-actions-deploy-role'
      AWS_REGION: 'ca-central-1'
      SECRETS_BUCKET: '583168578067-ca-central-1-static'
